version: "3.8"
services:
  database:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 66613300
    volumes:
      - video_site_pg_data:/var/lib/postgresql/data
volumes:
  video_site_pg_data:
