# Generated by Django 4.2.5 on 2023-11-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(max_length=512)),
                ('video_count', models.IntegerField()),
                ('info', models.JSONField()),
            ],
        ),
    ]
